name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd client && npm ci
    
    - name: Build client
      run: cd client && npm run build
    
    - name: Run tests
      run: npm test || true # Since we haven't set up tests yet
    
    - name: Build Docker image
      run: docker build -t voting-app .
      
  # Uncomment this section when you're ready to deploy to OpenShift
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - uses: actions/checkout@v3
  #   
  #   - name: Install OpenShift CLI
  #     uses: redhat-actions/openshift-tools-installer@v1
  #     with:
  #       oc: latest
  #   
  #   - name: Log in to OpenShift
  #     uses: redhat-actions/oc-login@v1
  #     with:
  #       openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
  #       openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
  #       insecure_skip_tls_verify: true
  #   
  #   - name: Deploy to OpenShift
  #     run: |
  #       oc project ${{ secrets.OPENSHIFT_NAMESPACE }}
  #       oc apply -f openshift-deployment.yaml 